enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  vite@*:
    dependencies:
      "@rollup/plugin-typescript": "*"
      typescript: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.8.1.cjs
