enableGlobalCache: false

nodeLinker: pnp
pnpMode: loose

yarnPath: .yarn/releases/yarn-4.8.1.cjs

packageExtensions:
  "react-cosmos-core@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "react-cosmos-renderer@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "react-cosmos-plugin-vite@*":
    dependencies:
      react-cosmos: "*"
  "vite@*":
    dependencies:
      supports-color: "*"
      rollup: "*"