yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: pnp
enableGlobalCache: false

pnpMode: loose # Vite 호환성 모드

packageExtensions:
  'vite@*':
    dependencies:
      '@rollup/plugin-typescript': '*'
      'typescript': '*'
