enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  react-cosmos-core@*:
    dependencies:
      react: "*"
      react-dom: "*"
  react-cosmos-plugin-vite@*:
    dependencies:
      react-cosmos: "*"
  react-cosmos-renderer@*:
    dependencies:
      react: "*"
      react-dom: "*"
  vite@*:
    dependencies:
      rollup: "*"
      supports-color: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.12.0.cjs
