name: Deploy to Vercel

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/student/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        working-directory: packages/student
        run: yarn install --immutable

      - name: Build Project
        working-directory: packages/student
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_STUDENT_URL: ${{ secrets.VITE_STUDENT_URL }}
          VITE_STUDENT_AUTH_URL: ${{ secrets.VITE_STUDENT_AUTH_URL }}
          VITE_STUDENT_COOKIE_DOMAIN: ${{ secrets.VITE_STUDENT_COOKIE_DOMAIN }}
          BRANCH: ${{ secrets.BRANCH }}
        run: yarn build

      - name: Deploy to Vercel
        working-directory: packages/student
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_STUDENT_URL: ${{ secrets.VITE_STUDENT_URL }}
          VITE_STUDENT_AUTH_URL: ${{ secrets.VITE_STUDENT_AUTH_URL }}
          VITE_STUDENT_COOKIE_DOMAIN: ${{ secrets.VITE_STUDENT_COOKIE_DOMAIN }}
          BRANCH: ${{ secrets.BRANCH }}
        run: |
          yarn global add vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --env VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} --env VITE_STUDENT_URL=${{ secrets.VITE_STUDENT_URL }} --env VITE_STUDENT_AUTH_URL=${{ secrets.VITE_STUDENT_AUTH_URL }} --env VITE_STUDENT_COOKIE_DOMAIN=${{ secrets.VITE_STUDENT_COOKIE_DOMAIN }} --env BRANCH=${{ secrets.BRANCH }}
